apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: auth
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm/myapps
      # version: '4.0.x'
      sourceRef:
        kind: GitRepository
        name: flux-system # name harus flux-system
        namespace: flux-system # namespace harus flux-system
      interval: 1m
  values:
    replicaCount: 2
    image: nginx:latest
    port: 80