apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./main/staging/namespaces
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system