apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: admin
  - literals:
      - NAME_SERVICE=admin
      - VERSION=v1.0