apiVersion: apps/v1
kind: Deployment
metadata:
  name: product
spec:
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
        - name: product
          image: aditirvan/load-test:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "68Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
