apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
spec:
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      volumes:
        - name: payment-gw-conf
          secret:
            secretName: payment-secret
      containers:
        - name: payment
          image: nginx:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
            requests:
              memory: "68Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: payment-gw-conf
              mountPath: /config/files
